export { Dashboard, Notifications } from "./pages/dashboard";
export { TeacherWorkspace } from "./pages/teacher";
export { Students, Admissions } from "./pages/students";
export { Attendance, Staff } from "./pages/attendance";
export { Finance } from "./pages/finance";
export { Reports, Administration } from "./pages/admin";
export { Academics } from "./pages/academics";
export { Curriculum } from "./pages/curriculum";
export { ManagementAlerts } from "./pages/alerts";
export { Intelligence, Platform } from "./pages/intelligence";
